name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Проверка кода из репозитория
    - name: Checkout Code
      uses: actions/checkout@v3

    # Установка .NET SDK 9
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    # Восстановление зависимостей
    - name: Restore Dependencies
      run: dotnet restore C:/Users/User/Desktop/suhanov/files/HW12/HW12

    # Сборка проекта
    - name: Build Project
      run: dotnet build --no-restore C:/Users/User/Desktop/suhanov/files/HW12/HW12

    # Запуск тестов
    - name: Run Unit Tests
      run: dotnet test C:/Users/User/Desktop/suhanov/files/HW12/HW12

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Проверка кода из репозитория
    - name: Checkout Code
      uses: actions/checkout@v3

    # Логин в Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Сборка Docker-образа
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hw12:latest C:/Users/User/Desktop/suhanov/files/HW12/HW12

    # Публикация Docker-образа
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/hw12:latest
