name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонируем репозиторий
    - name: Check out the repository
      uses: actions/checkout@v3

    # Шаг 2: Устанавливаем .NET SDK
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    # Шаг 3: Восстанавливаем зависимости
    - name: Restore dependencies
      run: dotnet restore HW12/HW12.csproj

    # Шаг 4: Собираем проект
    - name: Build the project
      run: dotnet build HW12/HW12.csproj --configuration Release

    # Шаг 5: Запускаем unit-тесты (если они есть)
    - name: Run tests
      run: dotnet test HW12/HW12.csproj --configuration Release

    # Шаг 6: Публикуем проект
    - name: Publish the project
      run: dotnet publish HW12/HW12.csproj --configuration Release --output ./out

    # Шаг 7: Собираем Docker-образ
    - name: Build Docker image
      run: |
        docker build -t Program -f HW12/Dockerfile HW12
